name: Build

on:
  push:
    tags:
      # ytf did they invent their own syntax that's almost regex?
      # ** matches 'zero or more of any character'
      - 'release-v[0-9]+.[0-9]+.[0-9]+**'
      - 'prerelease-v[0-9]+.[0-9]+.[0-9]+**'
  workflow_dispatch: # allows you to trigger manually

jobs:
  build_wheels:
    uses: explosion/gha-cibuildwheel/.github/workflows/cibuildwheel.yml@main
    permissions:
      contents: write
      actions: read
    with:
      wheel-name-pattern: "confection-*.whl"
      pure-python: true
      create-release: ${{ startsWith(github.ref, 'refs/tags/release-') || startsWith(github.ref, 'refs/tags/prerelease-') }}
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}
