name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  workflow_dispatch: # allows you to trigger manually

jobs:
  build_wheels:
    uses: explosion/gha-cibuildwheel/.github/workflows/cibuildwheel.yml@main
    permissions:
      contents: write
      actions: read
    with:
      wheel-name-pattern: "confection-*.whl"
      pure-python: true
      create-release: ${{ startsWith(github.ref, 'refs/tags/release-') || startsWith(github.ref, 'refs/tags/prerelease-') }}
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}
